name: build test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Build Mod
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: bug-splatter
          path: build/libs/*.jar
